In [2]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

/home/patryk/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [4]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [5]:
sequence = "I've been waiting for a HuggingFace course my whole life."
sequence_tokens = tokenizer.tokenize(sequence)

In [31]:
sequence2 = "I hate this so much!" 
sequence2_tokens = tokenizer.tokenize(sequence2)

In [42]:
sequence_ids = tokenizer.convert_tokens_to_ids(sequence_tokens)
sequence2_ids = tokenizer.convert_tokens_to_ids(sequence2_tokens)

In [ ]:
print(sequence2_ids)
print(model(torch.tensor([sequence2_ids])).logits) 

[1045, 5223, 2023, 2061, 2172, 999]
tensor([[ 3.1931, -2.6685]], grad_fn=<AddmmBackward0>)


In [44]:
attention_mask = [[],[]]

for i in range(len(sequence_ids)):
    attention_mask[0].append(1) 
    if i >= len(sequence2_ids): 
        sequence2_ids.append(tokenizer.pad_token_id)

for i in range(len(sequence_ids)):
    if sequence2_ids[i] == 0: 
        attention_mask[1].append(0)
    else:
        attention_mask[1].append(1)

In [45]:
print(model(torch.tensor([sequence_ids])).logits)


tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


In [46]:
batched_ids = [sequence_ids,sequence2_ids]
print(len(sequence2_ids),len(attention_mask[1]))
output = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(output.logits)

14 14
tensor([[-2.7276,  2.8789],
        [ 3.1931, -2.6685]], grad_fn=<AddmmBackward0>)
